name: Incremental Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Github Tag Bump and `latest` tag update
        uses: WiktorJ/github-tag-action@2.0.0
            