name: Incremental Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set output
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Check output
      env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}

    - name: Calculate new tag
      id: calculate_new_tag
      run: |
        latest_tag=${{ steps.get_latest_tag.outputs.LATEST_TAG }}
        
        if [[ $latest_tag == v* ]]; then
          latest_tag=${latest_tag:1}
        fi
        
        IFS='.' read -r -a parts <<< "$latest_tag"
        major=${parts[0]}
        minor=${parts[1]}
        patch=${parts[2]}
        
        # Increment patch version
        new_patch=$((patch + 1))
        new_tag="v$major.$minor.$new_patch"
        
        echo "New tag: $new_tag"
        echo "::set-output name=NEW_TAG::$new_tag"

    - name: Create new tag and push (if not exists)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        new_tag=${{ steps.calculate_new_tag.outputs.NEW_TAG }}
        
        # Check if tag already exists on the remote
        if git rev-parse -q --verify "refs/tags/$new_tag" >/dev/null; then
          echo "Tag $new_tag already exists. Skipping tag creation."
        else
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag $new_tag
          git push origin $new_tag
        fi
        